# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Quick Start"
  url = "/quickstart.html"
  weight = 20

[[main]]
  name = "User Guide"
  url = "/documentation.html"
  weight = 30

[[main]]
  name = "Dev Guide"
  url = "/developer.html"
  weight = 35

[[main]]
  name = "Publications"
  url = "/publication.html"
  weight = 40

[[main]]
  name = "License"
  url = "/license.html"
  weight = 50

[[main]]
  name = "Contact"
  url = "/contact.html"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
